### ISSUE TITLE
HI, I am also graduated from BNUZ, do you mind exchange any contact information?

### ISSUE THREAD

**Issue by koalaGreener** [af913337456/SlowlyProgressBar#1]
I am now studying at UCL, and I have studied in BNUZ before. I just can't find any contact information about you on your on blogs or Github, so I have to submit that issues. My email address is weijie.huang@ucl.ac.uk, hope that we can have a talk.

**Comment by af913337456** [comment]
Email: 913337456@qq.com
QQ: 913337456
WeChat: af913337456
